'use client'

import { useState } from 'react'
import { ToolPageShell } from '@/components/tools/ToolPageShell'
import { Download } from 'lucide-react'

export default function QRCodePage() {
  const [text, setText] = useState('')
  const [size, setSize] = useState(300)
  const [ecc, setEcc] = useState<'L' | 'M' | 'Q' | 'H'>('M')
  const [qrUrl, setQrUrl] = useState('')

  const generate = () => {
    if (!text.trim()) return
    const url = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}&ecc=${ecc}&format=png`
    setQrUrl(url)
  }

  const download = () => {
    if (!qrUrl) return
    const a = document.createElement('a')
    a.href = qrUrl
    a.download = 'qrcode.png'
    a.click()
  }

  return (
    <ToolPageShell groupId="dev" groupLabel="Developer Tools" groupHref="/tools/dev" groupColor="orange"
      toolLabel="QR Code Generator" description="Generate QR codes from any text or URL. Download as PNG.">
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5">Text / URL</label>
          <textarea value={text} onChange={e => setText(e.target.value)} rows={3}
            placeholder="https://example.com or any text"
            className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-orange-500 resize-none" />
        </div>

        <div className="flex flex-wrap gap-4">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Size: {size}px</label>
            <input type="range" min={100} max={600} step={50} value={size} onChange={e => setSize(parseInt(e.target.value))}
              className="accent-orange-600" />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Error Correction</label>
            <select value={ecc} onChange={e => setEcc(e.target.value as 'L'|'M'|'Q'|'H')}
              className="px-2 py-1 text-sm border border-gray-300 dark:border-gray-700 rounded bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
              <option value="L">L (7%)</option>
              <option value="M">M (15%)</option>
              <option value="Q">Q (25%)</option>
              <option value="H">H (30%)</option>
            </select>
          </div>
        </div>

        <button onClick={generate} disabled={!text.trim()} className="px-5 py-2 bg-orange-600 text-white text-sm font-medium rounded-lg hover:bg-orange-700 disabled:opacity-50">
          Generate QR Code
        </button>

        {qrUrl && (
          <div className="flex flex-col items-center gap-4 p-6 rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={qrUrl} alt="QR Code" width={size} height={size} className="rounded-lg" />
            <button onClick={download} className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800">
              <Download className="w-4 h-4" />
              Download PNG
            </button>
          </div>
        )}

        <p className="text-xs text-gray-400">QR codes are generated by api.qrserver.com. Content is sent to their servers.</p>
      </div>
    </ToolPageShell>
  )
}
